# Catch per Unite Effort (CPUE): standardize the number of fish caught by the amout of effort used to catch them
# Awhitten adapted from Ogle 2016 Chapter 2
# June 29, 2021
###################################

#---Notes---#
# LTEF annual report calculates CPUE for species in the upper Illinois River (BLG,CCF,LMB,SMB) and the lower Illinois River (Crappies,BLG,CCF,LMB,WHB,SCP)

# LTEF effort is one 15min electrofishing run and converted to fish per hour for the report (CPUE=#fish/(15/60))

# Remember to replace spaces with underscores from column names generated by LTEF master database. Names in caps. 
###################################

#---Packages----#
library(FSA)
library(magrittr)
library(dplyr)
library(tidyr)
###################################

#---Directory---#
getwd()
setwd ("//server/users/awhitten/Documents/LTEF/Annual_Report_LTEF")

# Read in data
fish<- read.csv("filename.csv")

#---Remove batched fish---# 
#multiplying rows by the count column
fish<-fish[rep(row.names(fish), fish$NUMBER),1:6]#rep is the function, new.data is data name, NUMBER is the column I want to multiply by, and 6 is my number of data columns
###NOTE above code means each row is a fish. Since this duplicates rows, the count column should all be ones. 
#---lower or upper river---#
# choose one
fish <- fish$REACH==c(I03,I04,I05)
fish <- fish$REACH==c(I06,I07,I08)

#---Effort---#
# Convert effort to per hour
fish <-fish %>% mutate(EF_EFFORT=EF_EFFORT/60)

#---catch---#
catch <- fish %>% group_by(LOCATION_CODE,SPECIES) %>% summarize(caught=sum(NUMBER)) %>% as.data.frame

#---Check for Zeros---#
# check if all data is there with location codes and species. Page 47 Ogle 2016

#---CPUE---#
# Catch of each species per hour
catch %>% mutate(cpue=caught/EF_EFFORT)
headtail(catch)

#---CPUE Summary Stats---#
cpueSum <- catch %>% group_by(SPECIES) %>% summarize(LOCATION_CODE=n(), fish=sum(caught), mean=mean(cupe), sd=sd(cupe), se=sd/sqrt(LOCATION_CODE), RSE=se/mean*100) %>% as.data.frame()
