# Catch per Unite Effort (CPUE): standardize the number of fish caught by the amount of effort used to catch them
# Created for one year of data
# Awhitten adapted from Ogle 2016 Chapter 2
# June 29, 2021
###################################

#---Notes---#
# LTEF annual report calculates CPUE for species in the upper Illinois River (BLG,CCF,LMB,SMB) and the lower Illinois River (Crappies(WHC and BLC),BLG,CCF,LMB,WHB,SCP) in both MCB-U (main channel boarder) and SCB (side channel boarder)

# LTEF effort is one 15min electrofishing run and converted to fish per hour for the report (CPUE=#fish/(15min/60min))

# Remember to replace spaces with underscores from column names generated by LTEF access master database. Names in caps also. 
###################################

#---Packages----#
library(FSA)
library(magrittr)
library(dplyr)
library(tidyr)
###################################

#---Directory---#
getwd()
setwd ("C:/Users/Kris/Documents/LTEF/Annual_Report_LTEF/LTEF")
setwd("\\\\server/users/awhitten/Documents/LTEF/Annual_Report_LTEF/LTEF")

# Read in data
# Used separate fish and site data to calculate catch and effort 
fish<- read.csv("LTEF2020_Report_Code.csv")
headtail(fish, n=2)
site<-read.csv("2020Sampling.csv")
headtail(site, n=2)

# select columns of needed data from fish dataset 
fish <- fish %>% select(YEAR,LOCATION_CODE,REACH,STRATUM,SPECIES, NUMBER) 
head(fish, n=2)

#---Remove batched fish---# 
#multiplying rows by the count column
fish<-fish[rep(row.names(fish), fish$NUMBER),1:6]#rep is the function, new.data is data name, NUMBER is the column I want to multiply by, and 6 is my number of data columns
###NOTE above code means each row is a fish. Since this duplicates rows, the count column should all be ones. 

#---Edit NUMBER Column---#
# b/c changed every row to one fish and use the NUMBER column later set it to 1
fish$NUMBER <-1
headtail(fish, n=2)

#---Effort---#
# Convert effort from minutes to hours (per hour)
site <-site %>% mutate(EF_EFFORT=EF_EFFORT/60)
headtail(site)
##################################################

#---Site Data lower/upper river & MCB-U/SCB---#
# Four separate Site Data frames used

# Upper Illinois River MCB Sites
site_ur_m <- site %>% filter(REACH %in% c("I03","I04","I05")) %>% filter(STRATUM=="MCB-U") %>% mutate(river="upper river")
headtail(site_ur_m)
# Upper Illinois River SCB Sites
site_ur_s <- fish %>% filter(REACH %in% c("I03","I04","I05")) %>% filter(STRATUM=="SCB") %>% mutate(river="upper river")

# Lower Illinois River MCB Sites
site_lr_m <- fish %>% filter(REACH %in% c("I06","I07","I08")) %>% filter(STRATUM=="MCB-U") %>% mutate(river="lower river")
# Lower Illinois River SCB Species
site_lr_s <- fish %>% filter(REACH %in% c("I06","I07","I08")) %>% filter(STRATUM=="SCB") %>% mutate(river="lower river")
###############################################

#---Fish Data lower/upper river & MCB-U/SCB & Species needed---#
# four separate fish data frames used

# Upper Illinois River MCB Species
fish_ur_m <- fish %>% filter(REACH %in% c("I03","I04","I05")) %>% filter(STRATUM=="MCB-U") %>% filter(SPECIES %in% c("BLG","CCF", "LMB", "SMB")) %>% mutate(river="upper river")
headtail(fish_ur_m)
# Upper Illinois River SCB Species
fish_ur_s <- fish %>% filter(REACH %in% c("I03","I04","I05")) %>% filter(STRATUM=="SCB") %>% filter(SPECIES %in% c("BLG","CCF", "LMB", "SMB")) %>% mutate(river="upper river")

# Lower Illinois River MCB Species
fish_lr_m <- fish %>% filter(REACH %in% c("I06","I07","I08")) %>% filter(STRATUM=="MCB-U") %>% filter(SPECIES %in% c("WHC", "BLC","BLG","CCF", "LMB", "WHB", "SCP")) %>% mutate(river="lower river")
# Lower Illinois River SCB Species
fish_lr_s <- fish %>% filter(REACH %in% c("I06","I07","I08")) %>% filter(STRATUM=="SCB") %>% filter(SPECIES %in% c("WHC", "BLC","BLG","CCF", "LMB", "WHB", "SCP")) %>% mutate(river="lower river")
###########################################

#---catch---#
# Upper River MCB-U & SCB
catch_ur_m <- fish_ur_m %>% group_by(LOCATION_CODE,SPECIES) %>% summarize(caught=sum(NUMBER),.groups = "keep") %>% as.data.frame

catch_ur_s <- fish_ur_s %>% group_by(LOCATION_CODE,SPECIES) %>% summarize(caught=sum(NUMBER),.groups = "keep") %>% as.data.frame

# Lower River MCB-U & SCB
catch_lr_m <- fish_lr_m %>% group_by(LOCATION_CODE,SPECIES) %>% summarize(caught=sum(NUMBER),.groups = "keep") %>% as.data.frame

catch_lr_s <- fish_lr_s %>% group_by(LOCATION_CODE,SPECIES) %>% summarize(caught=sum(NUMBER),.groups = "keep") %>% as.data.frame
###############################################

#---Join Catch and EFFort---#
catch_ur_m <-left_join(site_ur_m,catch_ur_m, by= "LOCATION_CODE", "SPECIES")
head(catch_ur_m)

catch_ur_s <-left_join(site_ur_s,catch_ur_s, by= "LOCATION_CODE", "SPECIES")

catch_lr_m <-left_join(site_lr_m,catch_lr_m, by= "LOCATION_CODE", "SPECIES")

catch_lr_s <-left_join(site_lr_s,catch_lr_s, by= "LOCATION_CODE", "SPECIES")
##################################################

#---Add Zeros---#
# Need to add zeros for locations that have no fish
catch_ur_m <- catch_ur_m %>% addZeroCatch("LOCATION_CODE", "SPECIES", zerovar="caught") %>% arrange(river,SPECIES, EF_EFFORT)

catch_ur_s <- catch_ur_s %>% addZeroCatch("LOCATION_CODE", "SPECIES", zerovar="caught") %>% arrange(river,SPECIES, EF_EFFORT)

catch_lr_m <- catch_lr_m %>% addZeroCatch("LOCATION_CODE", "SPECIES", zerovar="caught") %>% arrange(river,SPECIES, EF_EFFORT)

catch_lr_s <- catch_lr_s %>% addZeroCatch("LOCATION_CODE", "SPECIES", zerovar="caught") %>% arrange(river,SPECIES, EF_EFFORT)
############################################

#---CPUE---#
# Catch of each species per hour for upper and lower river MCB-U and SCB
catch_ur_m <- catch_ur_m %>% mutate(cpue=caught/EF_EFFORT)
headtail(catch_ur_m, n=2)
catch_ur_s <- catch_ur_s %>% mutate(cpue=caught/EF_EFFORT)
catch_lr_m <- catch_lr_m %>% mutate(cpue=caught/EF_EFFORT)
catch_lr_m <- catch_lr_s %>% mutate(cpue=caught/EF_EFFORT)
##############################################

#---CPUE Summary Stats---#
# Upper River MCB-U
cpueSum_ur_m <- catch_ur_m %>% group_by(SPECIES) %>% summarize(sites=n(), fish=sum(caught), mean=mean(cpue), sd=sd(cpue), se=sd/sqrt(sites), RSE=se/mean*100) %>% as.data.frame()

# Upper River SCB
cpueSum_ur_s <- catch_ur_s %>% group_by(SPECIES) %>% summarize(sites=n(), fish=sum(caught), mean=mean(cpue), sd=sd(cpue), se=sd/sqrt(sites), RSE=se/mean*100) %>% as.data.frame()

# Lower River MCB-U
cpueSum_lr_m <- catch_lr_m %>% group_by(SPECIES) %>% summarize(sites=n(), fish=sum(caught), mean=mean(cpue), sd=sd(cpue), se=sd/sqrt(sites), RSE=se/mean*100) %>% as.data.frame()

# Lower River SCB
cpueSum_lr_s <- catch_lr_s %>% group_by(SPECIES) %>% summarize(sites=n(), fish=sum(caught), mean=mean(cpue), sd=sd(cpue), se=sd/sqrt(sites), RSE=se/mean*100) %>% as.data.frame()
#############################################3

#---CPUE Graphs---#