# Condition of fish using Relative Weight Analyses (Wr)
#A measurement of physical health of a population of fish based on the relative heaviness or plumpness of fish in that population
# Awhitten through the use of Ogle, 2016 chapter 8
# June 29, 2021
####################################

#---Notes---#
# LTEF annual report usually only calculates Wr for Silver Carp in the lower Illinois River.

# Remember to replace spaces with underscores from column names generated by LTEF master database. Names in caps.

# Must do these calculations for both MCB (main channel boarder) and SCB (side channel boarder) and plot together.
####################################

#---packages---# 
library(FSA)
library(car) #before dplyr to reduce conflicts with MASS
library(magrittr)
library(dplyr) #sometimes command "select" will not run because of conflict with MASS
library(plotrix)
library(multcomp)
############################

#---Directory---#
getwd()
setwd ("//server/users/awhitten/Documents/LTEF/Annual_Report_LTEF") 

# Read in data
fish<- read.csv("filename.csv")

# Filter data & log weight and length
fish<-fish %>% mutate(logW=log10(WEIGHT), logL=log10(WEIGHT), LENGTH>160)
headtail(fish, n=2)
#remove fish below minimum to minimize mean variance ratio for species length>wsBLG[["min.TL"]]) or >160 mm SCP and >290 mm BHC

#----Species Coeff----#
#Standard weight equation coefficients for a particular species (Neumann et al. 2012)
#http://www.imsbio.co.jp/RGM/R_rdfile?f=FSA/man/wsVal.Rd&d=R_CC
#wsVal(species="List", units=("metric"), ref=75, simplify =TRUE)# shows all species for metric

#Species Selection using FSA
#wsVal("Bluegill", units="English", ref=75) #check length min and max!
#wsBLG<-wsVal("Bluegill", simplify = TRUE) #coefficient extracted 
#wsBLG

#---Sliver Carp---# 
#Ws equation total length (tl) millimeters and weight in grams
# log10Ws=-5.15756 + 3.06842(log10tl) Lamer 2015
#Lamer, J. T. (2015). Bighead and silver carp hybridization in the Mississippi River Basin: Prevalence, distribution, and post-zygotic selection. Doctoral dissertation. Champaign, IL: University of Illinois at Urbana-Champaign.

wsSCP<-c(int=-5.15756, slope=3.06842) # sliver carp intercept and slope


#---Bighead Carp---#
# log10Ws=-4.65006 + 2.88934(log10tl) Lamer 2015 
wsBHC<-c(int=-4.65006, slope=2.88934) # intercept and slope


#---Wr---#
#Calculate Wr using equation needed for variables provided by wsVal (see page 157 Ogle, 2016)
fish%<>%mutate(Ws=10^(wsSCP[["int"]]+wsSCP[["slope"]]*logL), Wr=wt/Ws*100)
headtail(fish, n=2) # Wr values <100 indicate fish weight below standard weight of fish of the same length

#---Wr Summary Stats---#
WrSum <- fish %>% group_by(YEAR) %>% summarize(LOCATION_CODE=n(), mean_Wr=mean(Wr), sd=sd(Wr), se=sd/sqrt(YEAR), RSE=se/mean*100) %>% as.data.frame()
############################

#---Plot Wr---#
# need to calculate average of all years to add long-term average lines for both MCB and SCB

