# Proportional Size Distribution (PSD): Size structure metric that calculates percentages of fish in Gablehouse Length Categories.
# Created for one year of data
# Awhitten adapted from Ogle 2016 Chapter 6 page 113
# July 1, 2021
###################################

#---Notes---#
# LTEF annual report calculates PSD for species in the upper Illinois River (BLG,CCF,LMB,SMB) and the lower Illinois River (Crappies(WHC and BLC),BLG,CCF,LMB,WHB) in both MCB-U (main channel boarder) and SCB (side channel boarder).

# Remember to replace spaces with underscores from column names generated by LTEF access master database. Names in caps also.
###################################

#---Packages----#
library(FSA)
library(magrittr)
library(dplyr)
library(plotrix)
library(Matching)
###################################

#---Directory---#
getwd()
setwd ("C:/Users/Kris/Documents/LTEF/Annual_Report_LTEF/LTEF")

# Read in data
# Used separate fish and site data to calculate catch and effort 
fish<- read.csv("LTEF2020_Report_Code.csv")
headtail(fish, n=2)

#---Remove batched fish---# 
#multiplying rows by the count column
fish<-fish[rep(row.names(fish), fish$NUMBER),1:6]#rep is the function, new.data is data name, NUMBER is the column I want to multiply by, and 6 is my number of data columns
###NOTE above code means each row is a fish. Since this duplicates rows, the count column should all be ones. 

#---Edit NUMBER Column---#
# b/c changed every row to one fish and use the NUMBER column later set it to 1
fish$NUMBER <-1
headtail(fish, n=2)

#---Fish Data lower/upper river & MCB-U/SCB & Species needed---#
# four separate fish data frames used

# Upper Illinois River MCB Species
fish_ur_m <- fish %>% filter(REACH %in% c("I03","I04","I05")) %>% filter(STRATUM=="MCB-U") %>% filter(SPECIES %in% c("BLG","CCF", "LMB", "SMB")) %>% mutate(river="upper river")
headtail(fish_ur_m)
# Upper Illinois River SCB Species
fish_ur_s <- fish %>% filter(REACH %in% c("I03","I04","I05")) %>% filter(STRATUM=="SCB") %>% filter(SPECIES %in% c("BLG","CCF", "LMB", "SMB")) %>% mutate(river="upper river")

# Lower Illinois River MCB Species
fish_lr_m <- fish %>% filter(REACH %in% c("I06","I07","I08")) %>% filter(STRATUM=="MCB-U") %>% filter(SPECIES %in% c("WHC", "BLC","BLG","CCF", "LMB", "WHB")) %>% mutate(river="lower river")
# Lower Illinois River SCB Species
fish_lr_s <- fish %>% filter(REACH %in% c("I06","I07","I08")) %>% filter(STRATUM=="SCB") %>% filter(SPECIES %in% c("WHC", "BLC","BLG","CCF", "LMB", "WHB")) %>% mutate(river="lower river")
######################################

#---Gabelhouse lengths for species---#
blg <- psdVal("Bluegill")
ccf <- psdVal("Channel Catfish")
lmb <- psdVal("Largemouth Bass")
smb <- psdVal("Smallmouth Bass")
whc <- psdVal("White Crappie")
blc <- psdVal("Black Crappie")
whb <- psdVal("White Bass")

# Break data into separate frames for each species??????????????????????
